
package pruebagestionlab;
import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

public class Principal extends javax.swing.JFrame {

   
    public Principal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Logo_Ingeomin_a_1.png")).getImage());
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSolicitud = new javax.swing.JLabel();
        BotonSolicitud = new javax.swing.JButton();
        BotonPersonal = new javax.swing.JButton();
        LabelPersonal = new javax.swing.JLabel();
        BotonInventario = new javax.swing.JButton();
        LabelInventario = new javax.swing.JLabel();
        BotonPresupuesto = new javax.swing.JButton();
        LabelPresupuesto = new javax.swing.JLabel();
        LabelPiePagina = new javax.swing.JLabel();
        LabelElaboradorPor = new javax.swing.JLabel();
        lblCliente_Muestra = new javax.swing.JLabel();
        botonTablaPeriodica = new javax.swing.JButton();
        botonAdministrador1 = new javax.swing.JButton();
        lblAdministrador = new javax.swing.JLabel();
        lblTablaPeriodica = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRINCIPAL - GENTION DE LABORATORIO -");
        setPreferredSize(new java.awt.Dimension(1090, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        LabelSolicitud.setForeground(java.awt.Color.black);
        LabelSolicitud.setText("Solicitud");
        getContentPane().add(LabelSolicitud);
        LabelSolicitud.setBounds(194, 264, 61, 15);

        BotonSolicitud.setBackground(new java.awt.Color(192, 160, 27));
        BotonSolicitud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Solicitud_180x180.png"))); // NOI18N
        BotonSolicitud.setPreferredSize(new java.awt.Dimension(181, 181));
        BotonSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSolicitud);
        BotonSolicitud.setBounds(135, 78, 180, 180);

        BotonPersonal.setBackground(new java.awt.Color(192, 160, 24));
        BotonPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Personal_180x180.png"))); // NOI18N
        BotonPersonal.setPreferredSize(new java.awt.Dimension(115, 118));
        BotonPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPersonal);
        BotonPersonal.setBounds(450, 77, 181, 181);

        LabelPersonal.setForeground(java.awt.Color.black);
        LabelPersonal.setText("Personal");
        getContentPane().add(LabelPersonal);
        LabelPersonal.setBounds(511, 264, 63, 15);

        BotonInventario.setBackground(new java.awt.Color(117, 126, 5));
        BotonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Inventario_180x180.png"))); // NOI18N
        BotonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonInventario);
        BotonInventario.setBounds(450, 354, 181, 181);

        LabelInventario.setForeground(java.awt.Color.black);
        LabelInventario.setText("Inventario");
        getContentPane().add(LabelInventario);
        LabelInventario.setBounds(515, 541, 72, 15);

        BotonPresupuesto.setBackground(new java.awt.Color(192, 160, 24));
        BotonPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Presupuesto_180x180.png"))); // NOI18N
        BotonPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPresupuestoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPresupuesto);
        BotonPresupuesto.setBounds(770, 77, 181, 181);

        LabelPresupuesto.setForeground(java.awt.Color.black);
        LabelPresupuesto.setText("Presupuesto");
        getContentPane().add(LabelPresupuesto);
        LabelPresupuesto.setBounds(795, 264, 91, 15);

        LabelPiePagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Diablo_a_15.png"))); // NOI18N
        getContentPane().add(LabelPiePagina);
        LabelPiePagina.setBounds(378, 590, 43, 35);

        LabelElaboradorPor.setForeground(java.awt.Color.black);
        LabelElaboradorPor.setText("Elaborado por: imosquerad@yahoo.com.mx");
        getContentPane().add(LabelElaboradorPor);
        LabelElaboradorPor.setBounds(427, 598, 306, 15);

        lblCliente_Muestra.setForeground(java.awt.Color.black);
        lblCliente_Muestra.setText("Cliente / Muestra");
        getContentPane().add(lblCliente_Muestra);
        lblCliente_Muestra.setBounds(161, 285, 121, 15);

        botonTablaPeriodica.setBackground(new java.awt.Color(117, 126, 5));
        botonTablaPeriodica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/tablaPeriodica.png"))); // NOI18N
        getContentPane().add(botonTablaPeriodica);
        botonTablaPeriodica.setBounds(770, 354, 181, 181);

        botonAdministrador1.setBackground(new java.awt.Color(117, 126, 5));
        botonAdministrador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Administrador.png"))); // NOI18N
        getContentPane().add(botonAdministrador1);
        botonAdministrador1.setBounds(134, 354, 181, 181);

        lblAdministrador.setText("Administrador");
        getContentPane().add(lblAdministrador);
        lblAdministrador.setBounds(173, 541, 100, 15);

        lblTablaPeriodica.setText("Tabla Periodica");
        getContentPane().add(lblTablaPeriodica);
        lblTablaPeriodica.setBounds(805, 541, 109, 15);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Fondo_1090_698.png"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -10, 1350, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSolicitudActionPerformed

         Cliente_Muestra construccion = new Cliente_Muestra();
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonSolicitudActionPerformed

    private void BotonPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPersonalActionPerformed
       Personal construccion = new Personal();
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonPersonalActionPerformed

    private void BotonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInventarioActionPerformed
        PaginaConstruccion construccion = new PaginaConstruccion();
        construccion.setBounds(0, 0, 350, 450);
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonInventarioActionPerformed

    private void BotonPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPresupuestoActionPerformed
        Presupuesto construccion = new Presupuesto();
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonPresupuestoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Principal construccion = new Principal();
        construccion.setBounds(0, 0, 1082, 656);
        construccion.setVisible(true);
        construccion.setResizable(false);
        construccion.setLocationRelativeTo(null);
        //this.setVisible(false);
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Principal().setVisible(true);
                               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonInventario;
    private javax.swing.JButton BotonPersonal;
    private javax.swing.JButton BotonPresupuesto;
    private javax.swing.JButton BotonSolicitud;
    private javax.swing.JLabel LabelElaboradorPor;
    private javax.swing.JLabel LabelInventario;
    private javax.swing.JLabel LabelPersonal;
    private javax.swing.JLabel LabelPiePagina;
    private javax.swing.JLabel LabelPresupuesto;
    private javax.swing.JLabel LabelSolicitud;
    private javax.swing.JButton botonAdministrador1;
    private javax.swing.JButton botonTablaPeriodica;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JLabel lblCliente_Muestra;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTablaPeriodica;
    // End of variables declaration//GEN-END:variables
}
