
package pruebagestionlab;

import javax.swing.DefaultListModel;
import static pruebagestionlab.TabPerioEleme.elementoE;
import static pruebagestionlab.TabPerioEleme.elemento;


public class tabPerioElementoSeleccion extends javax.swing.JInternalFrame {
        public static DefaultListModel elemento = new DefaultListModel();
    
    public tabPerioElementoSeleccion() {
        initComponents();
        
        elemento = new DefaultListModel();
        
        //escrito.add(listaVentanaAuxSeleccion);
        
       
        
        //ventana1.setVisible(true);
        
       // ventana1.setVisible(true);
         //this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaVentanaAuxSeleccion = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tabla Perio Elemento Seleccion");

        listaVentanaAuxSeleccion.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane1.setViewportView(listaVentanaAuxSeleccion);

        jButton1.setText("Aceptar Elementos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         //TabPerioEleme ventana1 = new TabPerioEleme();
         //ventana1.setVisible(true);
         //this.setVisible(false);
         TabPerioEleme ventana1 = new TabPerioEleme();
        elemento.addElement(ventana1.elementoE);
        System.out.println(elemento);
        listaVentanaAuxSeleccion.setModel(elemento);
        this.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaVentanaAuxSeleccion;
    // End of variables declaration//GEN-END:variables

        
    
}
