
package pruebagestionlab;

import java.io.BufferedReader;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class TxtJTable extends javax.swing.JFrame {
    DefaultListModel lista = new DefaultListModel();
        
    

    /**
     * Creates new form TxtJTable
     */
    public TxtJTable() {
        initComponents();
        new ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Logo_Ingeomin_a_1.png")).getImage();
        lista = new DefaultListModel();
        listaPresupuesto.setModel(lista);
        LeeArchivoTxt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        listaPresupuesto = new javax.swing.JList<>();
        lblDiablo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Listadatos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(listaPresupuesto);

        lblDiablo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebagestionlab/Imagenes/Diablo_a_1.png"))); // NOI18N

        lblNombre.setText("Nombre:");

        btnAgregar.setText("Agregar");
        btnAgregar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnAgregarItemStateChanged(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        Listadatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListadatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Listadatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(198, 198, 198)
                                .addComponent(lblDiablo))
                            .addComponent(lblNombre))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiablo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnAgregarItemStateChanged
        
        
    }//GEN-LAST:event_btnAgregarItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
         /*String mensaje = null;
        mensaje = Listadatos.getSelectedValue().toString();
        lista.addElement(mensaje); */             
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void ListadatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListadatosMouseClicked
        String mensaje = null;
        mensaje = Listadatos.getSelectedValue().toString();
        lista.addElement(mensaje);
        
    }//GEN-LAST:event_ListadatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TxtJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TxtJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TxtJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TxtJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TxtJTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Listadatos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDiablo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> listaPresupuesto;
    // End of variables declaration//GEN-END:variables

    public void LeeArchivoTxt() {

        BufferedReader almacenamiento;
        String cadena;
        String[] analisi = new String[3];
        analisi[0] = "";
        analisi[1] = "";
        analisi[2] = "";
        try {
            almacenamiento = new BufferedReader(new java.io.FileReader("ListaPrecio.txt"));
            cadena = "";
            
            DefaultListModel lista = new DefaultListModel();
            
            lista.addElement("TITULO DE LA TABLA");
            //(sCadena = bf.readLine())!=null
            while ((cadena = almacenamiento.readLine())!= null) {
                //cadena.split("\\,*");
                //String miString = linea.split(«separador»)[0];
                //int miEntero = Integer.parseInt(linea.split(«separador»)[1]);
                analisi[0] = cadena.split("\\t").toString();
                analisi[1] = cadena.split("\\t").toString();
                analisi[2] = cadena.split("\\t").toString();
                //System.out.println(analisi[0] + "  " + analisi[1] + "   " + analisi[2]);
                lista.addElement(cadena);  // ojo investigar + sobre .split **** .split("\t")
                
                //lista.toString().split("\\t,*");
            }
            Listadatos.setModel(lista);

            almacenamiento.close();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }  

    private Vector String() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class Strin {

        public Strin() {
        }
    }

    private static class Array {

        public Array() {
        }
    }

    private static class analisi {

        public analisi() {
            java.lang.String[] analisi = null;
            analisi[0]="";
             analisi[1]="";
              analisi[2]="";
        }
    }
}
